- name: style
  color: "1D76DB"
  description: "스타일 관련 기능(코드 포맷팅, 세미콜론 누락, 코드 자체의 변경이 없는 경우)"

- name: docs
  color: "F9D0C4"
  description: "문서 수정"

- name: feat
  color: "2ECC40"
  description: "새로운 기능 추가"

- name: fix
  color: "E74C3C"
  description: "버그 수정"

- name: refactor
  color: "9B59B6"
  description: "코드 리펙토링" 

- name: chore
  color: "3498DB"
  description: "빌드 업무 수정, 패키지 매니저 수정(ex .gitignore 수정 같은 경우)" 